POST http://127.0.0.1:5000/api/expenses/
Content-Type: application/json

{
  "amount": 250,
  "category": "Food",
  "description": "Lunch"
}
###
POST http://127.0.0.1:5000/api/expenses/
Content-Type: application/json

{
  "category": "Food"
}

###
GET http://127.0.0.1:5000/api/expenses/

###
GET http://127.0.0.1:5000/api/expenses/1

###
PATCH  http://127.0.0.1:5000/api/expenses/1
Content-Type: application/json

{
  "amount": 999,
  "category": "Gaming"
}

###
DELETE http://127.0.0.1:5000/api/expenses/1

###
GET http://127.0.0.1:5000/api/expenses/ai-insights
Content-Type: application/json

### Get all expenses
GET https://spendwise-ai-mn0e.onrender.com/api/expenses/

###
http://127.0.0.1:5000/api/budget?month=3&year=2026
Content-Type: application/json

###
POST http://127.0.0.1:5000/api/budget
Content-Type: application/json

{
  "amount": 10000,
  "month": 3,
  "year": 2026
}

###
GET http://127.0.0.1:5000/api/budget/history
Content-Type: application/json